# Generated by Django 5.2.9 on 2026-03-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Online Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('cod', 'Cash on Delivery'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('paymob', 'Paymob')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='concentration',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
