# Generated by Django 5.2.9 on 2026-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_order_notes_alter_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_thumbnail', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
