# Generated by Django 5.2.9 on 2026-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
