# Generated by Django 5.2.9 on 2026-03-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_banner_options_remove_banner_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(blank=True, help_text='e.g. Free shipping for orders over $2000', max_length=255, null=True)),
                ('announcement_link', models.URLField(blank=True, help_text='Optional link when clicking the top bar', max_length=500, null=True)),
                ('is_announcement_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
